export const actionTypes = {
    user: {
        SET_AUTH: "SET_AUTH",
        USER_REGISTER: 'USER_REGISTER',
        USER_REGISTER_PENDING: 'USER_REGISTER_PENDING',
        USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
        USER_REGISTER_ERROR: 'USER_REGISTER_ERROR',

        USER_LOGIN: 'USER_LOGIN',
        USER_LOGIN_PENDING: 'USER_LOGIN_PENDING',
        USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
        USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

        USER_LOGOUT: 'USER_LOGOUT',
        USER_LOGOUT_PENDING: 'USER_LOGOUT_PENDING',
        USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
        USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
    },
    task: {
        ADD_TASK: "ADD_TASK",
        ADD_TASK_PENDING: "ADD_TASK_PENDING",
        ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
        ADD_TASK_ERROR: "ADD_TASK_ERROR",

        GET_TASK: "GET_TASK",
        GET_TASK_PENDING: "GET_TASK_PENDING",
        GET_TASK_SUCCESS: "GET_TASK_SUCCESS",
        GET_TASK_ERROR: "GET_TASK_ERROR",

        DELETE_TASK: "DELETE_TASK",
        DELETE_TASK_PENDING: "DELETE_TASK_PENDING",
        DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
        DELETE_TASK_ERROR: "DELETE_TASK_ERROR",

        GET_ALL_TASK: "GET_ALL_TASK",
        GET_ALL_TASK_PENDING: "GET_ALL_TASK_PENDING",
        GET_ALL_TASK_SUCCESS: "GET_ALL_TASK_SUCCESS",
        GET_ALL_TASK_ERROR: "GET_ALL_TASK_ERROR",

        GET_ALL_BUCKET_TASK: "GET_ALL_BUCKET_TASK",
        GET_ALL_BUCKET_TASK_PENDING: "GET_ALL_BUCKET_TASK_PENDING",
        GET_ALL_BUCKET_TASK_SUCCESS: "GET_ALL_BUCKET_TASK_SUCCESS",
        GET_ALL_BUCKET_TASK_ERROR: "GET_ALL_BUCKET_TASK_ERROR",

        ADD_BUCKET_TASK: "ADD_BUCKET_TASK",
        ADD_BUCKET_TASK_PENDING: "ADD_BUCKET_TASK_PENDING",
        ADD_BUCKET_TASK_SUCCESS: "ADD_BUCKET_TASK_SUCCESS",
        ADD_BUCKET_TASK_ERROR: "ADD_BUCKET_TASK_ERROR",

        GET_BUCKET_TASK: "GET_BUCKET_TASK",
        GET_BUCKET_TASK_PENDING: "GET_BUCKET_TASK_PENDING",
        GET_BUCKET_TASK_SUCCESS: "GET_BUCKET_TASK_SUCCESS",
        GET_BUCKET_TASK_ERROR: "GET_BUCKET_TASK_ERROR",

        DELETE_BUCKET_TASK: "DELETE_BUCKET_TASK",
        DELETE_BUCKET_TASK_PENDING: "DELETE_BUCKET_TASK_PENDING",
        DELETE_BUCKET_TASK_SUCCESS: "DELETE_BUCKET_TASK_SUCCESS",
        DELETE_BUCKET_TASK_ERROR: "DELETE_BUCKET_TASK_ERROR",

    }
}